name: aud_cli
description: Manages many things around audanika software development.
version: 1.0.0
repository: https://github.com/inlavigo/aud_cli

environment:
  sdk: ^3.2.0

dependencies:
  path: ^1.8.0
  args: ^2.4.2

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.21.45
  test: ^1.24.0
  yaml: ^3.1.2
