name: aud_cli
description: The audanika developer command line
version: 1.0.0
repository: https://github.com/inlavigo/aud_cli
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  path: ^1.8.0
  args: ^2.4.2
  aud_cli_create_dart_package:
    git: git@github.com:inlavigo/aud_cli_create_dart_package.git
  aud_cli_gc:
    git: git@github.com:inlavigo/aud_cli_gc.git
  gg_check:
    git: git@github.com:inlavigo/gg_check.git
  colorize: ^3.0.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.22.0
  test: ^1.24.0
  yaml: ^3.1.2
