name: gg
description: The developer command line for maintaining all of our repos
version: 1.0.0
repository: https://github.com/inlavigo/gg
publish_to: none

environment:
  sdk: ^3.2.0

dependencies:
  path: ^1.8.0
  args: ^2.4.2
  gg_cli_cp:
    git: git@github.com:inlavigo/gg_cli_cp.git
  gg_cli_cc:
    git: git@github.com:inlavigo/gg_cli_cc.git
  gg_check:
    git: git@github.com:inlavigo/gg_check.git
  colorize: ^3.0.0

dev_dependencies:
  coverage: ^1.7.2
  lints: ^3.0.0
  pana: ^0.22.0
  test: ^1.24.0
  yaml: ^3.1.2
